version: '3.8'

services:
  api:
    container_name: chat-application
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest-chat-db
      - JWT_SECRET=Anubhav@20025
      - JWT_EXPIRY=1h
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mongo-db
    image: mongo:8.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
